#!/usr/bin/env bash

src=0

while [ $# != 0 ]; do
 flag="$1"
 case "$flag" in
  -s) echo "source is being copied as well ... "
      src=1
   ;;
   *) echo "Unrecognized flag or argument: $flag"
      exit 1
   ;;
 esac
 shift
done

prefix=SSE_
suffix=$(date '+%y%m%d')
foldernamename=$prefix$suffix
checkfoldernamename=$(ls | grep -w $foldernamename)
if [ "$checkfoldernamename" != "" ]
then
 suffix=$(date '+%y%m%d%H%M')
 foldernamename=$prefix$suffix
fi
echo "The back up folder is" $foldernamename

mkdir $foldernamename
mkdir $foldernamename/"_data"
cp "_data"/*.dat "_data"/ProcCtrl.txt "_data"/feat.msg $foldernamename/"_data"/.
mkdir $foldernamename/"_mesh"
cp partitioner prt_bin sse_bin sse_install sse_start $foldernamename/.
mkdir $foldernamename/"_vtk"
mkdir $foldernamename/"_dump"
mkdir $foldernamename/"_1D"
mkdir $foldernamename/"_RTD"
mkdir $foldernamename/"_hist"
cp -r KMB $foldernamename/.

if [ ${src} == 1 ]
then
 cp *.pvsm Makefile CMakeLists.txt $foldernamename/.
 cp -r "cmake" $foldernamename/.
 rm -rf source/*~
 rm -rf source/*/*~
 cp -r source $foldernamename/.
 mkdir $foldernamename/"o"
fi

exit 1