#!/usr/bin/env bash

user_suffix=""

while getopts "s:" options; do

  case $options in
    s) if [ "$OPTARG" != "" ] ; then
         user_suffix=$OPTARG
         echo "User suffix: $user_suffix";
       else
         echo "The -s option does not contain a valid suffix";
       fi;;
  esac  
done

checkfoldernamename=$(ls | grep -w source)
if [ "$checkfoldernamename" == "" ]
then
 echo "This is not a right folder (source is missing...)"
 exit 1
fi

prefix=bu_ParQ2P1_
suffix=$(date '+%y%m%d')
if [ "$user_suffix" == ""  ] ; then
  foldernamename=$prefix$suffix
else
  foldernamename=$prefix$user_suffix
fi


checkfoldernamename=$(ls | grep -w $foldernamename)
if [ "$checkfoldernamename" != "" ]
then
 suffix=$(date '+%y%m%d%H%M')
 foldernamename=$prefix$suffix
fi

echo "The back up folder is" $foldernamename

mkdir $foldernamename
rm -rf source/*~
rm -rf source/*/*~
cp -r source $foldernamename/.
mkdir $foldernamename/"_data"
cp "_data"/*.dat "_data"/ProcCtrl.txt "_data"/feat.msg $foldernamename/"_data"/.
mkdir $foldernamename/"_mesh"
cp -r "_adc" $foldernamename/.
cp -r "cmake" $foldernamename/.

if [ -d "FullC0ntact" ]; then
  echo "Directory FullC0ntact exists."
  cp -r "FullC0ntact" $foldernamename
fi

cp Makefile merger partitioner updateWithFC update LiDoscript Hostfile Description.txt CMakeLists.txt $foldernamename/.
mkdir $foldernamename/"_gmv"
mkdir $foldernamename/"_vtk"
mkdir $foldernamename/"_ns"
mkdir $foldernamename/"o"
mkdir $foldernamename/"_gmv"/"frames"
mkdir $foldernamename/"_gmv"/"temp"

