#!/bin/bash
cp ./testcases/fac/_data/q2p1_param.dat _data
cp ./testcases/fac/start/data.TXT start
mpirun -np 5 ./q2p1
cp _data/prot.txt fac_new_prot.txt
echo "Test Results" >> ./testresults/results.txt
echo "Newtonian: Drag Lift" >> ./testresults/results.txt
grep 'Force acting' fac_new_prot.txt | tail -1 | awk '{print ""$7" "$8""}' >> ./testresults/results.txt

