#!/bin/bash
cp ./testcases/fac_nnewt/_data/q2p1_param.dat _data
cp ./testcases/fac_nnewt/start/data.TXT start
mpirun -np 5 ./q2p1
cp _data/prot.txt fac_nnew_prot.txt
echo "Non-Newtonian: Drag Lift" >> ./testresults/results.txt
grep 'Force acting' fac_nnew_prot.txt | tail -1 | awk '{print ""$7" "$8""}' >> ./testresults/results.txt

