C
      SUBROUTINE ParIA237(VA,KCOL,KLD,DX,DB,DD,NEQ,NIT,OMEGA,ILEV)
C
      USE PP3D_MPI
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      DIMENSION VA(*),KCOL(*),KLD(*),DX(*),DB(*),DD(*)
      COMMON /ERRCTL/ IER,ICHECK
      SAVE /ERRCTL/
C
      IF (ICHECK.GE.998) CALL OTRC('IA237 ','10/26/89')
C
      DO 1 ITE=1,NIT
C
      CALL LCL1(DD,NEQ)
      DO 2 IEQ=1,NEQ
      DO 3 ICOL=KLD(IEQ)+1,KLD(IEQ+1)-1
3     DD(IEQ)=DD(IEQ)-DBLE(VA(ICOL))*DX(KCOL(ICOL))
2     CONTINUE
C
      CALL CommSum(DD,ILEV)
C
      DO 4 IEQ=1,NEQ
4     DD(IEQ)=DD(IEQ)+DB(IEQ)
      DO 5 IEQ=1,NEQ
5     DX(IEQ)=(1D0-OMEGA)*DX(IEQ)+
     *         OMEGA*DD(IEQ)/DBLE(mg_mpi(ILEV)%UE(IEQ))
C
1     CONTINUE
C
      END
C
C
C 
      SUBROUTINE ParIA217(DA,KCOL,KLD,DX,DB,DD,NEQ,NIT,OMEGA,ILEV)
C
      USE PP3D_MPI
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      DIMENSION DA(*),KCOL(*),KLD(*),DX(*),DB(*),DD(*)
      COMMON /ERRCTL/ IER,ICHECK
      SAVE /ERRCTL/
C
      IF (ICHECK.GE.998) CALL OTRC('IA217 ','10/26/89')
C
      DO 1 ITE=1,NIT
      CALL LCL1(DD,NEQ)
      DO 2 IEQ=1,NEQ
      DO 3 ICOL=KLD(IEQ)+1,KLD(IEQ+1)-1
3     DD(IEQ)=DD(IEQ)-DA(ICOL)*DX(KCOL(ICOL))
2     CONTINUE
C
      CALL CommPres(DD,DX,ILEV)
C
      DO 4 IEQ=1,NEQ
4     DD(IEQ)=DD(IEQ)+DB(IEQ)
      DO 5 IEQ=1,NEQ
5     DX(IEQ)=(1D0-OMEGA)*DX(IEQ)+OMEGA*DD(IEQ)/DA(KLD(IEQ))
1     CONTINUE
C
      END
C
C
C
      SUBROUTINE PArIB237(VA,KCOL,KLD,DX,DB,DD,NEQ,NIT,ILEV)
C
      USE PP3D_MPI
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      DIMENSION VA(*),KCOL(*),KLD(*),DX(*),DB(*),DD(*)
      COMMON /ERRCTL/ IER,ICHECK
      SAVE /ERRCTL/
C
      IF (ICHECK.GE.998) CALL OTRC('IB237 ','01/09/89')
C
      DO 1 ITE=1,NIT
C
      CALL LCL1(DD,NEQ)
C
      DO 2 IEQ=1,NEQ
      DO 3 ICOL=KLD(IEQ)+1,KLD(IEQ+1)-1
3     DD(IEQ)=DD(IEQ)-DBLE(VA(ICOL))*DX(KCOL(ICOL))
2     CONTINUE

      CALL CommSum(DD,ILEV)

      DO 4 IEQ=1,NEQ
      DD(IEQ)=DD(IEQ)+DB(IEQ)
4     DX(IEQ)=DD(IEQ)/DBLE(mg_mpi(ILEV)%UE(IEQ))

1     CONTINUE
C
      END
C
C
C
      SUBROUTINE ParIB217(DA,KCOL,KLD,DX,DB,DD,NEQ,NIT,ILEV)
C
      USE PP3D_MPI
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      DIMENSION DA(*),KCOL(*),KLD(*),DX(*),DB(*),DD(*)
      COMMON /ERRCTL/ IER,ICHECK
      SAVE /ERRCTL/
C
      IF (ICHECK.GE.998) CALL OTRC('IB217 ','01/02/89')
C
      DO 1 ITE=1,NIT
C
      CALL LCL1(DD,NEQ)
C
      DO 2 IEQ=1,NEQ
      DO 3 ICOL=KLD(IEQ)+1,KLD(IEQ+1)-1
3     DD(IEQ)=DD(IEQ)-DA(ICOL)*DX(KCOL(ICOL))
2     CONTINUE
C
      CALL CommPres(DD,DX,ILEV)
      CALL LLC1 (DB,DD,NEQ,1d0,1D0)
C
      DO 4 IEQ=1,NEQ
4     DX(IEQ)=DD(IEQ)/DA(KLD(IEQ))
C
1     CONTINUE
C
      END
C
C
C
      SUBROUTINE ParIC237(VA,KCOL,KLD,DX,DB,DD,NEQ,NIT,OMEGA,ILEV)
C
      USE PP3D_MPI
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      DIMENSION VA(*),KCOL(*),KLD(*),DX(*),DB(*),DD(*)
      COMMON /ERRCTL/ IER,ICHECK
      SAVE /ERRCTL/
C
      IF (ICHECK.GE.998) CALL OTRC('IC237 ','10/27/89')
C
      DO 1 ITE=1,NIT
C
      DO 2 IEQ=1,NEQ
      DD(IEQ)=0d0
      DO 3 ICOL=KLD(IEQ)+1,KLD(IEQ+1)-1
3     DD(IEQ)=DD(IEQ)-DBLE(VA(ICOL))*DX(KCOL(ICOL))
2     CONTINUE
C
      CALL CommSum(DD,ILEV)
      CALL LLC1 (DB,DD,NEQ,1d0,1D0)
C
      DO 4 IEQ=1,NEQ
4     DX(IEQ)=OMEGA*(DD(IEQ)/
     *DBLE(mg_mpi(ILEV)%UE(IEQ))-DX(IEQ))+DX(IEQ)
C
1     CONTINUE
C
      END
C
C
C
      SUBROUTINE ParIC217(DA,KCOL,KLD,DX,DB,DD,NEQ,NIT,OMEGA,ILEV)
C
      USE PP3D_MPI
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      DIMENSION DA(*),KCOL(*),KLD(*),DX(*),DB(*),DD(*)
      COMMON /ERRCTL/ IER,ICHECK
      SAVE /ERRCTL/
C
      IF (ICHECK.GE.998) CALL OTRC('IC217 ','10/27/89')
C
      DO 1 ITE=1,NIT
C
      DO 2 IEQ=1,NEQ
      DD(IEQ)=0d0
      DO 3 ICOL=KLD(IEQ)+1,KLD(IEQ+1)-1
3     DD(IEQ)=DD(IEQ)-DA(ICOL)*DX(KCOL(ICOL))
2     CONTINUE
C
      CALL CommPres(DD,DX,ILEV)
      CALL LLC1 (DB,DD,NEQ,1d0,1D0)
C
      DO 4 IEQ=1,NEQ
4     DX(IEQ)=OMEGA*(DD(IEQ)/DA(KLD(IEQ))-DX(IEQ))+DX(IEQ)
C
1     CONTINUE
C
      END
C
C
C
      SUBROUTINE ParID237(VA,KCOL,KLD,DX,DB,DD,NEQ,NIT,OMEGA,ILEV)
C
      USE PP3D_MPI
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      DIMENSION VA(*),KCOL(*),KLD(*),DX(*),DB(*),DD(*)
      COMMON /ERRCTL/ IER,ICHECK
      SAVE /ERRCTL/
C
      IF (ICHECK.GE.998) CALL OTRC('ID237 ','01/02/89')
C
!       WRITE(*,*) "Sorry, this smoother does not work"
!       CALL MPI_Finalize(IERR)
C
      DO 5 ITE=1,NIT
C
      DO 1 IEQ=1,NEQ
      DD(IEQ)=0D0
      ILD=KLD(IEQ)
      DO 2 ICOL=ILD+1,KLD(IEQ+1)-1
      IF (KCOL(ICOL).GE.IEQ) GOTO 1
2     DD(IEQ)=DD(IEQ)+DBLE(VA(ICOL))*DX(KCOL(ICOL))
1     CONTINUE
C
      CALL CommSum(DD,ILEV)

      DO 3 IEQ=1,NEQ
3     DX(IEQ)=(DX(IEQ)-DD(IEQ)*OMEGA)/
     *DBLE(mg_mpi(ILEV)%UE(IEQ))
C
      DO 10 IEQ=NEQ-1,1,-1
      DD(IEQ)=0D0
      ILD=KLD(IEQ)
      DO 12 ICOL=ILD+1,KLD(IEQ+1)-1
      IF (KCOL(ICOL).LE.IEQ) GOTO 12
      DD(IEQ)=DD(IEQ)+DBLE(VA(ICOL))*DX(KCOL(ICOL))
12    CONTINUE
10    CONTINUE
C
      CALL CommSum(DD,ILEV)
C
      DO IEQ=NEQ-1,1,-1
       DX(IEQ)=DX(IEQ)-DD(IEQ)*OMEGA/
     * DBLE(mg_mpi(ILEV)%UE(IEQ))
      END DO
C
5     CONTINUE
C
      END
C
C
C
      SUBROUTINE ParID217(DA,KCOL,KLD,DX,DB,DD,NEQ,NIT,OMEGA,ILEV)
C
      USE PP3D_MPI
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      DIMENSION DA(*),KCOL(*),KLD(*),DX(*),DB(*),DD(*)
      COMMON /ERRCTL/ IER,ICHECK
      SAVE /ERRCTL/
C
      IF (ICHECK.GE.998) CALL OTRC('ID217 ','01/02/89')
C
!       WRITE(*,*) "Sorry, this smoother does not work"
!       CALL MPI_Finalize(IERR)
C
      DO 5 ITE=1,NIT
C
      DO 1 IEQ=1,NEQ
      DD(IEQ)=0D0
      ILD=KLD(IEQ)
      DO 2 ICOL=ILD+1,KLD(IEQ+1)-1
      IF (KCOL(ICOL).GE.IEQ) GOTO 1
2     DD(IEQ)=DD(IEQ)+DA(ICOL)*DX(KCOL(ICOL))
1     CONTINUE
C
      CALL CommPres(DD,DX,ILEV)
C
      DO 3 IEQ=1,NEQ
3     DX(IEQ)=(DX(IEQ)-DD(IEQ)*OMEGA)/DA(ILD)
C
      DO 10 IEQ=NEQ-1,1,-1
      DD(IEQ)=0D0
      ILD=KLD(IEQ)
      DO 12 ICOL=ILD+1,KLD(IEQ+1)-1
      IF (KCOL(ICOL).LE.IEQ) GOTO 12
      DD(IEQ)=DD(IEQ)+DA(ICOL)*DX(KCOL(ICOL))
12    CONTINUE
10    CONTINUE
C
      CALL CommPres(DD,DX,ILEV)
C
      DO 13 IEQ=NEQ-1,1,-1
13    DX(IEQ)=DX(IEQ)-DD(IEQ)*OMEGA/DA(ILD)
C
5     CONTINUE
C
      END
C
C
C
      SUBROUTINE ParIF237 (VA,VC,KCOL,KLD,DX,DB,DD,NEQ,NIT,OMEGA,ILEV)
C
      USE PP3D_MPI
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      DIMENSION VA(*),VC(*),KCOL(*),KLD(*),DX(*),DB(*),DD(*)
      REAL*8, DIMENSION(:), ALLOCATABLE :: ILUMat
C
      ALLOCATE (ILUMat(NEQ))
C
      DO 10 ITE=1,NIT
      CALL LAX37(VA,KCOL,KLD,NEQ,DX,DD,-1D0,0D0)
C
      CALL CommSum(DD,ILEV)
      CALL LLC1 (DB,DD,NEQ,1d0,1D0)
C
      CALL ParIF137(VC,KCOL,KLD,DD,ILUMat,NEQ,ILEV)
      CALL LLC1 (DD,DX,NEQ,OMEGA,1D0)
10    CONTINUE
C
      DEALLOCATE (ILUMat)
C
      END
C
C
C
      SUBROUTINE ParIF217 (DA,VC,KCOL,KLD,DX,DB,DD,NEQ,NIT,OMEGA,ILEV)
C
      USE PP3D_MPI
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      DIMENSION DA(*),VC(*),KCOL(*),KLD(*),DX(*),DB(*),DD(*)
      REAL*8, DIMENSION(:), ALLOCATABLE :: ILUMat
C
      ALLOCATE (ILUMat(NEQ))
C
      DO 10 ITE=1,NIT
      CALL LAX17(DA,KCOL,KLD,NEQ,DX,DD,-1D0,0D0)
C
      CALL CommPres(DD,DX,ILEV)
      CALL LLC1 (DB,DD,NEQ,1d0,1D0)
C
      CALL ParIF117(VC,KCOL,KLD,DD,ILUMat,NEQ,ILEV)
      CALL LLC1 (DD,DX,NEQ,OMEGA,1D0)
10    CONTINUE
C
      DEALLOCATE (ILUMat)
C
      END
C
C
C
      SUBROUTINE ParIF137(VA,KCOL,KLD,DX,DD,NEQ,ILEV)
      USE PP3D_MPI
C
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      DIMENSION VA(*),KCOL(*),KLD(*),DX(*),DD(*)
      COMMON /ERRCTL/ IER,ICHECK
      SAVE /ERRCTL/
C
      IF (ICHECK.GE.998) CALL OTRC('IF137 ','12/02/89')
C
      DO 501 IEQ=2,NEQ
      DD(IEQ)=0D0
      DO 502 JCOL=KLD(IEQ)+1,KLD(IEQ+1)-1
      ICOL=KCOL(JCOL)
      IF (ICOL.GE.IEQ) GOTO 501
502   DD(IEQ)=DD(IEQ)+DBLE(VA(JCOL))*DX(ICOL)
501   CONTINUE
C
      CALL CommSum(DD,ILEV)
      CALL LLC1(DD,DX,NEQ,-1d0,1d0) !DX(IEQ)=DX(IEQ)-AUX
C
      DX(NEQ)=DX(NEQ)/DBLE(mg_mpi(ILEV)%UE(NEQ))
      DO 503 IEQ=NEQ-1,1,-1
      ILD=KLD(IEQ)
      DD(IEQ)=0D0
      DO 504 JCOL=KLD(IEQ+1)-1,ILD+1,-1
      ICOL=KCOL(JCOL)
      IF (ICOL.LE.IEQ) GOTO 503
      DD(IEQ)=DD(IEQ)+DBLE(VA(JCOL))*DX(ICOL)
504   CONTINUE
503   CONTINUE
C
      CALL CommSum(DD,ILEV)
C
      DO IEQ=NEQ-1,1,-1
      DX(IEQ)=(DX(IEQ)-DD(IEQ))/DBLE(mg_mpi(ILEV)%UE(IEQ))
      END DO
C
      END
C
C
C
      SUBROUTINE ParIF117(VA,KCOL,KLD,DX,DD,NEQ,ILEV)
      USE PP3D_MPI
C
      IMPLICIT DOUBLE PRECISION (A,C-H,O-U,W-Z),LOGICAL(B)
      DIMENSION VA(*),KCOL(*),KLD(*),DX(*),DD(*)
      COMMON /ERRCTL/ IER,ICHECK
      SAVE /ERRCTL/
C
      IF (ICHECK.GE.998) CALL OTRC('IF117 ','12/02/89')
C
      DO 501 IEQ=2,NEQ
      DD(IEQ)=0D0
      DO 502 JCOL=KLD(IEQ)+1,KLD(IEQ+1)-1
      ICOL=KCOL(JCOL)
      IF (ICOL.GE.IEQ) GOTO 501
502   DD(IEQ)=DD(IEQ)+DBLE(VA(JCOL))*DX(ICOL)
501   CONTINUE

      CALL CommPres(DD,DX,ILEV)
      CALL LLC1(DD,DX,NEQ,-1d0,1d0) !DX(IEQ)=DX(IEQ)-AUX
C
      DX(NEQ)=DX(NEQ)/DBLE(VA(KLD(NEQ)))
      DO 503 IEQ=NEQ-1,1,-1
      ILD=KLD(IEQ)
      DD(IEQ)=0D0
      DO 504 JCOL=KLD(IEQ+1)-1,ILD+1,-1
      ICOL=KCOL(JCOL)
      IF (ICOL.LE.IEQ) GOTO 503
      DD(IEQ)=DD(IEQ)+DBLE(VA(JCOL))*DX(ICOL)
504   CONTINUE
503   CONTINUE
C
      CALL CommPres(DD,DX,ILEV)
C
      DO IEQ=NEQ-1,1,-1
      DX(IEQ)=(DX(IEQ)-DD(IEQ))/DBLE(VA(KLD(IEQ)))
      END DO
C
      END
C
C
C
      ! This routine is not prepared ....!!!!!!
      SUBROUTINE ParVYAX7(VA,KCOL,KLD,NEQ,DY,DX1,DX2,DYAX1,DYAX2)
C
      USE PP3D_MPI
      IMPLICIT REAL*8 (A,C-H,O-U,W-Z),LOGICAL(B)
      DIMENSION VA(*),KCOL(*),KLD(*),DX1(*),DX2(*),DY(*)
C
      DYAX1=0D0
      DYAX2=0D0
C
      DO 1 IROW=1,NEQ
      DYIROW=DY(IROW)
      IF (DYIROW.EQ.0D0) GOTO 1
      AUX1=0D0
      AUX2=0D0
C
      DO 2 ICOL=KLD(IROW),KLD(IROW+1)-1
      JCOL=KCOL(ICOL)
      DAICOL=DBLE(VA(ICOL))
      IF (DAICOL.EQ.0D0) GOTO 2
      AUX1=AUX1+DAICOL*DX1(JCOL)
      AUX2=AUX2+DAICOL*DX2(JCOL)
2     CONTINUE
C
      DYAX1=DYAX1+AUX1*DYIROW
      DYAX2=DYAX2+AUX2*DYIROW
1     CONTINUE
C
      END
