      SUBROUTINE XGMV3D(MUNIT,CFILE,cmesh,NEL,NVT,
     *           VU,VV,VW,VP,VNU,VRT,TIMENS)
      USE PP3D_MPI
      IMPLICIT DOUBLE PRECISION(A,C-H,O-U,W-Z),LOGICAL(B)
C
      CHARACTER SUB*6,FMT*15,CPARAM*120
      CHARACTER CFILE*(20),cmesh*(20)
      DIMENSION VU(*),VV(*),VW(*),VP(*),VNU(*),VRT(*)
C
      COMMON /ERRCTL/ IER,ICHECK
      COMMON /CHAR/   SUB,FMT(3),CPARAM
      COMMON /OUTPUT/ M,MT,MKEYB,MTERM,MERR,MPROT,MSYS,MTRC,IRECL8
      SAVE
C
C
C
      IF (myid.eq.MASTER) RETURN
C
      OPEN (UNIT=MUNIT,FILE=CFILE)
C
      WRITE(MUNIT,'(A)')'gmvinput ascii'
C
      WRITE(UNIT=MUNIT,FMT=*) 'nodes fromfile "',TRIM(cmesh),'"'
      WRITE(UNIT=MUNIT,FMT=*) 'cells fromfile "',TRIM(cmesh),'"'
C
      WRITE(MUNIT,*)  'velocity 1'
      DO 130 IVT=1,NVT
130   WRITE(MUNIT,1000) VU(IVT)
      DO 140 IVT=1,NVT
140   WRITE(MUNIT,1000) VV(IVT)
      DO 150 IVT=1,NVT
150   WRITE(MUNIT,1000) VW(IVT)

      WRITE(MUNIT,*)  'variable'

      WRITE(MUNIT,*)  'pressure 1'
      DO 160 IVT=1,NVT
160   WRITE(MUNIT,1000) VP(IVT)

      WRITE(MUNIT,*)  'DistFunc 1'
      DO 170 IVT=1,NVT
170   WRITE(MUNIT,1000) VNU(IVT)

      WRITE(MUNIT,*)  'vorticity 1'
      DO 180 IVT=1,NVT
180   WRITE(MUNIT,1000) VRT(IVT)

      WRITE(MUNIT,*)  'endvars'
      WRITE(MUNIT,*)  'probtime ',REAL(TIMENS)
      WRITE(MUNIT,*)  'endgmv'
C
C
      REWIND (MUNIT)
      CLOSE  (MUNIT)
C
C
1000  FORMAT(E12.5)
1100  FORMAT(8I8)
C
      END
C
C
C
      SUBROUTINE XGMVMS(MUNIT,cmesh,NEL,NVT,KVERT,DCORVG)
      IMPLICIT DOUBLE PRECISION(A,C-H,O-U,W-Z),LOGICAL(B)
C
      CHARACTER SUB*6,FMT*15,CPARAM*120
      CHARACTER cmesh*(20)
      DIMENSION KVERT(8,*),DCORVG(3,*)
C
      COMMON /ERRCTL/ IER,ICHECK
      COMMON /CHAR/   SUB,FMT(3),CPARAM
      COMMON /OUTPUT/ M,MT,MKEYB,MTERM,MERR,MPROT,MSYS,MTRC,IRECL8
      SAVE
C
C
C
      OPEN (UNIT=MUNIT,FILE=cmesh)
C
      WRITE(MUNIT,'(A)')'gmvinput ascii'
      WRITE(MUNIT,*)'nodes ',NVT
C
      DO 100 IVT=1,NVT
100   WRITE(MUNIT,1000) REAL(DCORVG(1,IVT))
      DO 101 IVT=1,NVT
101   WRITE(MUNIT,1000) REAL(DCORVG(2,IVT))
      DO 102 IVT=1,NVT
102   WRITE(MUNIT,1000) REAL(DCORVG(3,IVT))
C
      WRITE(MUNIT,*)'cells ',NEL
      DO 110 IEL=1,NEL
      WRITE(MUNIT,*)'hex 8'
110   WRITE(MUNIT,1100) KVERT(1,IEL),KVERT(2,IEL),
     *                  KVERT(3,IEL),KVERT(4,IEL),
     *                  KVERT(5,IEL),KVERT(6,IEL),
     *                  KVERT(7,IEL),KVERT(8,IEL)
C
C
       WRITE(MUNIT,*)  'endgmv'
C
C
      REWIND (MUNIT)
      CLOSE  (MUNIT)
C
C
1000  FORMAT(E12.5)
1100  FORMAT(8I8)
C
      END
C
C
C
      SUBROUTINE XGID3D(MUNIT,CFILE,NEL,NVT,VU,VV,VW,VP,VNU,ICOUNT)
C
	IMPLICIT DOUBLE PRECISION(A,C-H,O-U,W-Z),LOGICAL(B)
C
      CHARACTER SUB*6,FMT*15,CPARAM*120
      CHARACTER CFILE*(20)
      DIMENSION VU(*),VV(*),VW(*),VP(*),VNU(*)
C
      COMMON /ERRCTL/ IER,ICHECK
      COMMON /CHAR/   SUB,FMT(3),CPARAM
      COMMON /OUTPUT/ M,MT,MKEYB,MTERM,MERR,MPROT,MSYS,MTRC,IRECL8
	SAVE
C
C
C
      OPEN (UNIT=MUNIT,FILE=CFILE)
      IF (ICOUNT.EQ.1) WRITE (MUNIT,*) ' '
C
      WRITE(MUNIT,*) "Velocities           4",ICOUNT,"'Featflow' 2 1 0"
      DO 200 IVT=1,NVT
200   WRITE(MUNIT,2000) IVT,VU(IVT),VV(IVT),VW(IVT)

      WRITE(MUNIT,*) "Pressures            4",ICOUNT,"'Featflow' 1 1 0"
      DO 210 IVT=1,NVT
210   WRITE(MUNIT,2100) IVT,VP(IVT)

      WRITE(MUNIT,*) "Turb_Visc            4",ICOUNT,"'Featflow' 1 1 0"
      DO 220 IVT=1,NVT
220   WRITE(MUNIT,2100) IVT,VNU(IVT)
C

      REWIND (MUNIT)
      CLOSE  (MUNIT)
C
C
2000  FORMAT(I8,3X,3(3X,E15.8))
2100  FORMAT(I8,3X,E15.8)
C
      END
C
C
C
      SUBROUTINE XGIDMS(MUNIT,CFILE,CFILE1,NEL,NVT,KVERT,DCORVG)
C
	IMPLICIT DOUBLE PRECISION(A,C-H,O-U,W-Z),LOGICAL(B)
C
      CHARACTER SUB*6,FMT*15,CPARAM*120
      CHARACTER CFILE*(20),CFILE1*(20)
      DIMENSION KVERT(8,*),DCORVG(3,*)
C
      COMMON /ERRCTL/ IER,ICHECK
      COMMON /CHAR/   SUB,FMT(3),CPARAM
      COMMON /OUTPUT/ M,MT,MKEYB,MTERM,MERR,MPROT,MSYS,MTRC,IRECL8
	SAVE
C
C
C
      OPEN (UNIT=MUNIT,FILE=CFILE)
C
      WRITE(MUNIT,*)'MESH "Featflow" dimension 3 Elemtype Hexahedra
     & Nnode 8'
      WRITE(MUNIT,*)'coordinates'
C
      DO 100 IVT=1,NVT
100   WRITE(MUNIT,1000) IVT,REAL(DCORVG(1,IVT)),REAL(DCORVG(2,IVT)),
     *                  REAL(DCORVG(3,IVT))
      WRITE(MUNIT,*)'end coordinates'
      WRITE(MUNIT,*)
      WRITE(MUNIT,*)'elements'
C
      DO 110 IEL=1,NEL
110   WRITE(MUNIT,1100) IEL,KVERT(1,IEL),KVERT(2,IEL),
     *                  KVERT(3,IEL),KVERT(4,IEL),KVERT(5,IEL),
     *                  KVERT(6,IEL),KVERT(7,IEL),KVERT(8,IEL)
      WRITE(MUNIT,*)'end elements'
C
C
      CLOSE(MUNIT)
C
      OPEN (UNIT=MUNIT,FILE=CFILE1,STATUS='REPLACE')
      WRITE(*,*) " "
      CLOSE(MUNIT)
C
1000  FORMAT(I8,3X,3(3X,E15.8))
1100  FORMAT(I8,3X,8(3X,I8))
C
      END
