set(Q2P1_BUILD_ID_FOUND false)

IF(Q2P1_BUILD_ID STREQUAL "nehalem-linux-intel-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} -O3 -funroll-loops -std=c++11")
  SET(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O3 -funroll-loops -std=c++11")
  SET(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} -O3 -xSSE4.2 -funroll-loops -assume underscore -assume buffered_io -fp-model precise -no-prec-div -fpp")
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "core2duo-linux-intel-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} -O3 -xSSE3 -funroll-loops -fp-model precise -no-prec-div -std=c++11")
  SET(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O3 -xSSE3 -funroll-loops -fp-model precise -no-prec-div -std=c++11")
  SET(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} -O3 -xSSE3 -funroll-loops -assume underscore -assume buffered_io -fp-model precise -no-prec-div -fpp")
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "i7-linux-intel-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} -O3 -xhost -funroll-loops -fp-model precise -no-prec-div -std=c++11")
  SET(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O3 -xhost -funroll-loops -fp-model precise -no-prec-div -std=c++11")
  SET(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} -O3 -xhost -funroll-loops -assume underscore -assume buffered_io -fp-model precise -no-prec-div -fpp")
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "xeon-linux-intel-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} -O3 -xhost -funroll-loops -fp-model precise -no-prec-div -std=c++11")
  SET(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O3 -xhost -funroll-loops -fp-model precise -no-prec-div -std=c++11")
  SET(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} -O3 -xhost -funroll-loops -assume underscore -assume buffered_io -fp-model precise -no-prec-div -fpp")
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "opteron-linux-intel-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} -O3 -funroll-loops -fp-model precise -no-prec-div -std=c++11")
  SET(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O3 -funroll-loops -fp-model precise -no-prec-div -std=c++11")
  SET(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} -O3 -funroll-loops -assume underscore -fp-model precise -no-prec-div -fpp")
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "opteronx2-linux-intel-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} -O3 -funroll-loops -fp-model precise -no-prec-div -std=c++11")
  SET(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O3 -funroll-loops -fp-model precise -no-prec-div -std=c++11")
  SET(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} -O3 -funroll-loops -assume underscore -fp-model precise -no-prec-div -fpp")
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "phenomIIx4-linux-intel-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} -O3 -funroll-loops -fp-model precise -no-prec-div -std=c++11")
  SET(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O3 -funroll-loops -fp-model precise -no-prec-div -std=c++11")
  SET(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} -O3 -funroll-loops -assume underscore -fp-model precise -no-prec-div -fpp")
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "phenomIIx4-linux-gcc-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} -O3 -march=amdfam10 -msse4a -ffast-math -funroll-loops")
  SET(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O3 -march=amdfam10 -msse4a -ffast-math -funroll-loops")
  SET(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} -O3 -march=amdfam10 -msse4a -ffast-math -funroll-loops -cpp")
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "opteronx2-linux-gcc-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} -O3 -m64 -mmmx -msse -msse2 -m3dnow -mfpmath=sse -ffast-math")
  SET(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O3 -m64 -mmmx -msse -msse2 -m3dnow -mfpmath=sse -ffast-math")
  SET(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} -O3 -m64 -mmmx -msse -msse2 -m3dnow -mfpmath=sse -ffast-math -cpp")
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "nehalem-linux-gcc-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} -O3 -march=native -std=c++11")
  SET(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O3 -march=native")
  SET(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} -O3 -march=native -finit-local-zero -ffixed-line-length-none -ffree-line-length-none -Wall")
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "xeon-linux-gcc-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} -O3 -march=native -std=c++11")
  SET(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O3 -march=native")
  SET(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} -O3 -march=native -finit-local-zero -ffixed-line-length-none -ffree-line-length-none -Wall")
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

#--------------------------------------------------------------------------------------------------------------------------------
#                                                      Debug builds
#--------------------------------------------------------------------------------------------------------------------------------

IF(Q2P1_BUILD_ID STREQUAL "opteron-linux-intel-debug")
  SET(CMAKE_BUILD_TYPE "Debug")
  SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} -g")
  SET(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -g")
  SET(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} -g -assume underscore -fpp")
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "opteronx2-linux-intel-debug")
  SET(CMAKE_BUILD_TYPE "Debug")
  SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} -g")
  SET(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -g")
  SET(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} -g -assume underscore -zero -fpp")
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

