# find lib2ds includes and library
#
# LIB2DS_INCLUDE_DIR - where the lib2ds directory containing the headers can be
#                      found
# LIB2DS_LIBRARY     - full path to the lib2ds library
# LIB2DS_FOUND       - TRUE if lib2ds was found

FIND_LIBRARY(FEATFLOW_UMFPACK4_LIBRARY NAMES UMFPACK4 umfpack4
             PATHS $ENV{FEATFLOW1_LIBDIR} )


IF(FEATFLOW_UMFPACK4_LIBRARY)
    MESSAGE(STATUS "Found libumfpack4 library: ${FEATFLOW_UMFPACK4_LIBRARY}")
ELSE(FEATFLOW_UMFPACK4_LIBRARY)
    MESSAGE(STATUS "Could NOT find libumfpack4 library.")
ENDIF(FEATFLOW_UMFPACK4_LIBRARY)


IF(FEATFLOW_UMFPACK4_LIBRARY)
    SET(FEATFLOW_FEAT2D_FOUND TRUE)
ELSE(FEATFLOW_UMFPACK4_LIBRARY)
    SET(FEATFLOW_FEAT2D_FOUND FALSE)
    IF(FEATFLOW_UMFPACK4_LIBRARY_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Featflow libumfpack4 not found")
    ENDIF(FEATFLOW_UMFPACK4_LIBRARY_FIND_REQUIRED)
ENDIF(FEATFLOW_UMFPACK4_LIBRARY)

