# find lib2ds includes and library
#
# LIB2DS_INCLUDE_DIR - where the lib2ds directory containing the headers can be
#                      found
# LIB2DS_LIBRARY     - full path to the lib2ds library
# LIB2DS_FOUND       - TRUE if lib2ds was found

FIND_LIBRARY(FEATFLOW_AMD_LIBRARY NAMES amd AMD
             PATHS ${CMAKE_SOURCE_DIR}/libs $ENV{FEATFLOW1_LIBDIR} )

IF(FEATFLOW_AMD_LIBRARY)
    MESSAGE(STATUS "Found libamd library: ${FEATFLOW_AMD_LIBRARY}")
ELSE(FEATFLOW_AMD_LIBRARY)
    MESSAGE(STATUS "Could NOT find libamd library.")
ENDIF(FEATFLOW_AMD_LIBRARY)


IF(FEATFLOW_AMD_LIBRARY)
    SET(FEATFLOW_FEAT2D_FOUND TRUE)
ELSE(FEATFLOW_AMD_LIBRARY)
    SET(FEATFLOW_FEAT2D_FOUND FALSE)
    IF(FEATFLOW_AMD_LIBRARY_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Featflow libamd not found")
    ENDIF(FEATFLOW_AMD_LIBRARY_FIND_REQUIRED)
ENDIF(FEATFLOW_AMD_LIBRARY)

