# find lib2ds includes and library
#
# LIB2DS_INCLUDE_DIR - where the lib2ds directory containing the headers can be
#                      found
# LIB2DS_LIBRARY     - full path to the lib2ds library
# LIB2DS_FOUND       - TRUE if lib2ds was found

FIND_LIBRARY(FEATFLOW_SYSUTILS_LIBRARY NAMES sysutils
  PATHS ${CMAKE_SOURCE_DIR}/libs $ENV{FEATFLOW1_LIBDIR} )


IF(FEATFLOW_SYSUTILS_LIBRARY)
    MESSAGE(STATUS "Found libsysutils library: ${FEATFLOW_SYSUTILS_LIBRARY}")
ELSE(FEATFLOW_SYSUTILS_LIBRARY)
    MESSAGE(STATUS "Could NOT find libsysutils library.")
ENDIF(FEATFLOW_SYSUTILS_LIBRARY)


IF(FEATFLOW_SYSUTILS_LIBRARY)
    SET(FEATFLOW_FEAT2D_FOUND TRUE)
ELSE(FEATFLOW_SYSUTILS_LIBRARY)
    SET(FEATFLOW_FEAT2D_FOUND FALSE)
    IF(FEATFLOW_SYSUTILS_LIBRARY_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Featflow libsysutils not found")
    ENDIF(FEATFLOW_SYSUTILS_LIBRARY_FIND_REQUIRED)
ENDIF(FEATFLOW_SYSUTILS_LIBRARY)

