
set(FF_DEFAULT_INCLUDE_PATH
  ${MPI_Fortran_INCLUDE_PATH}
  ${CMAKE_SOURCE_DIR}/source/include
  #${Boost_INCLUDE_DIR}
  )

set(FF_APPLICATION_INCLUDE_PATH
  ${MPI_Fortran_INCLUDE_PATH}
  ${CMAKE_SOURCE_DIR}/source/include
  ${CMAKE_BINARY_DIR}
  #${Boost_INCLUDE_DIR}
  )


if(USE_MUMPS)

  set(MUMPS_STRUCTURES_INCLUDE_PATH
    ${CMAKE_SOURCE_DIR}/extern/libraries/MUMPS_5.0.1/include
    )

  list(APPEND FF_DEFAULT_INCLUDE_PATH ${MUMPS_STRUCTURES_INCLUDE_PATH})

  list(APPEND FF_APPLICATION_INCLUDE_PATH ${MUMPS_STRUCTURES_INCLUDE_PATH})

endif(USE_MUMPS)

if(USE_HYPRE)

  set(HYPRE_STRUCTURES_INCLUDE_PATH
    ${CMAKE_SOURCE_DIR}/extern/libraries/hypre/src/
    )

  list(APPEND FF_DEFAULT_INCLUDE_PATH ${HYPRE_STRUCTURES_INCLUDE_PATH})

  list(APPEND FF_APPLICATION_INCLUDE_PATH ${HYPRE_STRUCTURES_INCLUDE_PATH})


endif(USE_HYPRE)


#message(STATUS "Libraries: ${FF_DEFAULT_INCLUDE_PATH}")  
#message(FATAL_ERROR "Application libraries: ${FF_APPLICATION_INCLUDE_PATH}")  
