
set(FF_DEFAULT_INCLUDE_PATH
  ${MPI_Fortran_INCLUDE_PATH}
  )

set(FF_APPLICATION_INCLUDE_PATH
  ${MPI_Fortran_INCLUDE_PATH}
  )


if(USE_MUMPS)

  set(MUMPS_STRUCTURES_INCLUDE_PATH
    ${CMAKE_SOURCE_DIR}/extern/libraries/MUMPS_5.0.1/include
    )

  list(APPEND FF_DEFAULT_INCLUDE_PATH ${MUMPS_STRUCTURES_INCLUDE_PATH})

  list(APPEND FF_APPLICATION_INCLUDE_PATH ${MUMPS_STRUCTURES_INCLUDE_PATH})

endif(USE_MUMPS)

#message(STATUS "Libraries: ${FF_DEFAULT_INCLUDE_PATH}")  
#message(FATAL_ERROR "Application libraries: ${FF_APPLICATION_INCLUDE_PATH}")  
