set(Q2P1_BUILD_ID_FOUND false)

IF(Q2P1_BUILD_ID STREQUAL "nehalem-linux-intel-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CXX_FLAGS_FC -xhost -funroll-loops -fp-model precise -no-prec-div -std=c++11)
  SET(Fortran_FLAGS -xhost -funroll-loops -assume underscore -assume buffered_io -fp-model precise -no-prec-div -fpp)
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "core2duo-linux-intel-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CXX_FLAGS_FC -xhost -funroll-loops -fp-model precise -no-prec-div -std=c++11)
  SET(Fortran_FLAGS -xhost -funroll-loops -assume underscore -assume buffered_io -fp-model precise -no-prec-div -fpp)
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "i7-linux-intel-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CXX_FLAGS_FC -xhost -funroll-loops -fp-model precise -no-prec-div -std=c++11)
  SET(Fortran_FLAGS -xhost -funroll-loops -assume underscore -assume buffered_io -fp-model precise -no-prec-div -fpp)
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "xeon-linux-intel-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CXX_FLAGS_FC -xhost -funroll-loops -fp-model precise -no-prec-div -std=c++11)
  SET(Fortran_FLAGS -xhost -funroll-loops -assume underscore -fp-model precise -no-prec-div -fpp)
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "opteron-linux-intel-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CXX_FLAGS_FC -xhost -funroll-loops -fp-model precise -no-prec-div -std=c++11)
  SET(Fortran_FLAGS -xhost -funroll-loops -assume underscore -assume buffered_io -fp-model precise -no-prec-div -fpp)
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "opteronx2-linux-intel-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CXX_FLAGS_FC -xhost -funroll-loops -fp-model precise -no-prec-div -std=c++11)
  SET(Fortran_FLAGS -xhost -funroll-loops -assume underscore -assume buffered_io -fp-model precise -no-prec-div -fpp)
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "phenomIIx4-linux-intel-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CXX_FLAGS_FC -xhost -funroll-loops -fp-model precise -no-prec-div -std=c++11)
  SET(Fortran_FLAGS -xhost -funroll-loops -assume underscore -assume buffered_io -fp-model precise -no-prec-div -fpp)
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "phenomIIx4-linux-gcc-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CXX_FLAGS_FC -march=native -std=c++11)
  SET(Fortran_FLAGS -march=native -finit-local-zero -ffixed-line-length-none -ffree-line-length-none -Wall -cpp)
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "opteronx2-linux-gcc-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CXX_FLAGS_FC -march=native -std=c++11)
  SET(Fortran_FLAGS -march=native -finit-local-zero -ffixed-line-length-none -ffree-line-length-none -Wall -cpp)
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "nehalem-linux-gcc-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CXX_FLAGS_FC -march=native -std=c++11)
  SET(Fortran_FLAGS -march=native -finit-local-zero -ffixed-line-length-none -ffree-line-length-none -Wall -cpp)
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "xeon-linux-gcc-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CXX_FLAGS_FC -march=native -std=c++11)
  SET(Fortran_FLAGS -march=native -finit-local-zero -ffixed-line-length-none -ffree-line-length-none -Wall -cpp)
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "i7-linux-gcc-release")
  SET(CMAKE_BUILD_TYPE "Release")
  SET(CXX_FLAGS_FC -march=native -std=c++11)
  SET(Fortran_FLAGS -march=native -finit-local-zero -ffixed-line-length-none -ffree-line-length-none -Wall -cpp)
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

#--------------------------------------------------------------------------------------------------------------------------------
#                                                      Debug builds
#--------------------------------------------------------------------------------------------------------------------------------

IF(Q2P1_BUILD_ID STREQUAL "opteron-linux-intel-debug")
  SET(CMAKE_BUILD_TYPE "Debug")
  SET(CXX_FLAGS_FC -std=c++11)
  SET(Fortran_FLAGS -assume underscore -fpp)
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "xeon-linux-intel-debug")
  SET(CMAKE_BUILD_TYPE "Debug")
  SET(CXX_FLAGS_FC -std=c++11)
  SET(Fortran_FLAGS -assume underscore -fpp)
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "xeon-linux-gcc-debug")
  SET(CMAKE_BUILD_TYPE "Debug")
  SET(CXX_FLAGS_FC -std=c++11)
  SET(Fortran_FLAGS -finit-local-zero -ffixed-line-length-none -ffree-line-length-none -Wall -cpp)
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

IF(Q2P1_BUILD_ID STREQUAL "opteronx2-linux-intel-debug")
  SET(CMAKE_BUILD_TYPE "Debug")
  SET(CXX_FLAGS_FC -std=c++11)
  SET(Fortran_FLAGS -assume underscore -fpp)
  SET(Q2P1_BUILD_ID_FOUND true)
ENDIF()

